# WebSocket 广播器配置文件 (自动生成)
# 此文件由系统自动创建，包含推荐的默认配置
# 请根据您的实际需求修改相关设置

server:
    host: 0.0.0.0
    port: "8765"
    path: /ws
database:
    type: memory
    redis:
        host: ""
        port: 0
        password: ""
        db: 0
    mysql:
        host: ""
        port: 0
        user: ""
        password: ""
        database: ""
    postgresql:
        host: ""
        port: 0
        user: ""
        password: ""
        database: ""
        sslmode: ""
    message_ttl: 3600
rules:
    - name: 监控转发
      from_sources:
        - '*'
      to_targets:
        - monitor_system
      message_types:
        - event
      enabled: false
      transform:
        prefix_event: '[监控] '
groups:
    - name: "逻辑验证测试组"
      members: 
        - creative
        - survival
        - test_client
        - qq_bot
      message_types: ["chat", "event"]
      enabled: true
      transform: {}
      blacklist:
        # 测试配置：server1,2,3之间互相
        - name: "服务器组内互相阻止"
          description: "测试from和to列表相同时的阻止逻辑"
          from: ["creative", "survival"]
          to: ["creative", "survival"]
          enabled: true
    - name: 事件广播
      members:
        - creative
        - survival
        - test_client
        - qq_bot
      message_types:
        - event
      enabled: true
      transform:
        prefix_event: '【事件】 '
clients:
    - name: minecraft_server
      url: ws://localhost:8766/ws
      auto_reconnect: true
      reconnect_interval: 5
    - name: qq_bot
      url: ws://localhost:8767/ws
      auto_reconnect: true
      reconnect_interval: 5
